name: "Dev Deploy"

on:
    push:
        branches-ignore:
            - 'main'
            - 'qual'

permissions:
  id-token: write
  contents: read

jobs: 
    preview:
        uses: ./.github/workflows/pipeline.yml
        with: 
            environment: dev