name: Android App APK Build

on: push

permissions:
  contents: read
  pull-requests: write

jobs:
  setup-eas:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Create preview
        if: github.ref_name == 'main'
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto

      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get version
        shell: bash
        run: |
          VERSION="$(jq -r '.expo.version' 'app.json')"
          echo $VERSION >> $GITHUB_OUTPUT

      - name: display version
        run: echo '${{ steps.outputs }}'
